name: MS Teams Deploy Card

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # this is the new step
      - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      - uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.AZURE_FUNCION_TRIGGER }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"commit": ${{ github.GITHUB_SHA }}, "keytest": "valuetest"}'


